# имя контейнера
app-web1:
  #докерфайл искать в указнной папке
  build: ./web
  # слушать по адресу 8081 то что в контейнере на 8080
  ports:
  - "8082:8080"
  # ссылается на другой контейнер
  links:
  - app-db1

# имя контейнера
app-db1:
  # докерфайл лежит тут
  build: ./db
  #слушать по адресу 5433 то что в контейнере на 5432
  ports:
  - "5434:5432"
  # подключить диски (разделы) с указанного контейнера
  volumes_from:
  - app-db-data1
# название контейнера
# 2 контейнера постгре чтобы докер помнил данные
# данные и процесс постгре на разных контейнерах
app-db-data1:
  # имя образа
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL'
  # подключить раздел
  volumes:
  - /var/lib/postgresql/data